# application name
appname: "SamRaymer::TwitterStuff"

### IMPORTANT
# Retrieve these keys from https://apps.twitter.com/ and store in the service's environment variables:
# TWITTER_CONSUMER_KEY
# TWITTER_CONSUMER_SECRET
# TWITTER_TOKEN
# TWITTER_TOKEN_SECRET

# number of tweets to return with GET /statuses/recent/:id
recent_tweet_count: 30

#per the twitter API
max_user_id_count: 5000

# we are running a JSON REST API 
# responses to users will serialize in json format
serializer: JSON

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# no default views in this app
layout: undef
